

export const SAVE_COVID_SUMMARY = 'GET_COVID_SUMMARY';
export const SAVE_DEATH_CASES = 'SAVE_DEATH_CASES';
export const SAVE_ACTIVE_CASES = 'SAVE_ACTIVE_CASES';
export const SAVE_RECOVERED_CASES = 'SAVE_RECOVERED_CASES';

export const FETCH_DATA_STARTED = 'FETCH_DATA_STARTED';
export const FETCH_DATA_COMPLETED = 'FETCH_DATA_COMPLETED';